app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('vino/',include(('applications.vino.urls' ,'vino'),namespace='vino')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/compras/urls.py
from django.urls import path , include

from .views import ComprasView, compras ,CompraDetDelete 
from .reportes import reporte_compras ,imprimir_compra

urlpatterns=[
    path('compras/',ComprasView.as_view(), name="listacompras"),
    path('compras/new',compras, name="compras_new"),
    path('compras/edit/<int:compra_id>',compras, name="editarcompra"),
    path('compras/<int:compra_id>/delete/<int:pk>',CompraDetDelete.as_view(), name="delete_detcompra"),
    path('compras/imprimirreportes/' ,reporte_compras, name='imprimirtodas'),
    path('compras/imprimiruna/<int:compra_id>/' , imprimir_compra , name='imprimiruna' ),
]

applications/compras/models.py
from django.db import models



#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from applications.bases.models import ClaseModelo
from applications.vino.models import Vino



class ComprasEnc(ClaseModelo):
    fecha_compra=models.DateField(null=True,blank=True)
    observacion=models.TextField(blank=True,null=True)
    total=models.FloatField(default=0)

   
    
    def __str__(self):
        return '{}'.format(self.observacion)
    def save(self):
        self.observacion = self.observacion.upper()
        super(ComprasEnc,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Compras"
        verbose_name="Encabezado Compra"

class ComprasDet(ClaseModelo):
    compra=models.ForeignKey(ComprasEnc,on_delete=models.CASCADE)
    vino=models.ForeignKey(Vino,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    sub_total=models.FloatField(default=0)
    precio=models.FloatField(default=0)
   
    

    def __str__(self):
        return '{}'.format(self.vino)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        super(ComprasDet, self).save()
    
    class Mega:
        verbose_name_plural = "Detalles Compras"
        verbose_name="Detalle Compra"


@receiver(post_save, sender=ComprasDet)
def detalle_compra_guardar(sender,instance,**kwargs):
    id_vino = instance.vino.id
    fecha_compra=instance.compra.fecha_compra
    print(fecha_compra)

    vino=Vino.objects.filter(pk=id_vino).first()
    if vino:
        cantidad = int(vino.existencia) + int(instance.cantidad)
        vino.existencia = cantidad
        vino.ultimacompra=fecha_compra
        print(vino.ultimacompra)
        vino.save()


@receiver(post_delete, sender=ComprasDet)
def detalle_compra_borrar(sender,instance, **kwargs):
    id_vino = instance.vino.id
    id_compra = instance.compra.id
    fecha_compra=instance.compra.fecha_compra

    enc = ComprasEnc.objects.filter(pk=id_compra).first()
    if enc:
        sub_total = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        print('--------------------' ,sub_total['sub_total__sum']) 
        if  sub_total['sub_total__sum'] is None or sub_total['sub_total__sum']==0:
            enc.total=0  
            print('!!!!!!!1funciona',enc.total) 
            enc.save()
        else:
            enc.total=sub_total['sub_total__sum']
            enc.save()
    
    vino=Vino.objects.filter(pk=id_vino).first()
    if vino:
        cant=int(instance.cantidad)
        ex=int(vino.existencia)
        if cant>ex:
            print('no se puede hacer')
        elif cant<=ex:
            cantidad = ex - cant
            vino.existencia = cantidad
            vino.ultimacompra=fecha_compra
            vino.save()

compras/models.py
from django.db import models



#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from bases.models import ClaseModelo
from vino.models import Vino



class ComprasEnc(ClaseModelo):
    fecha_compra=models.DateField(null=True,blank=True)
    observacion=models.TextField(blank=True,null=True)
    total=models.FloatField(default=0)

   
    
    def __str__(self):
        return '{}'.format(self.observacion)
    def save(self):
        self.observacion = self.observacion.upper()
        super(ComprasEnc,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Compras"
        verbose_name="Encabezado Compra"

class ComprasDet(ClaseModelo):
    compra=models.ForeignKey(ComprasEnc,on_delete=models.CASCADE)
    vino=models.ForeignKey(Vino,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    sub_total=models.FloatField(default=0)
    precio=models.FloatField(default=0)
   
    

    def __str__(self):
        return '{}'.format(self.vino)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        super(ComprasDet, self).save()
    
    class Mega:
        verbose_name_plural = "Detalles Compras"
        verbose_name="Detalle Compra"


@receiver(post_save, sender=ComprasDet)
def detalle_compra_guardar(sender,instance,**kwargs):
    id_vino = instance.vino.id
    fecha_compra=instance.compra.fecha_compra
    print(fecha_compra)

    vino=Vino.objects.filter(pk=id_vino).first()
    if vino:
        cantidad = int(vino.existencia) + int(instance.cantidad)
        vino.existencia = cantidad
        vino.ultimacompra=fecha_compra
        print(vino.ultimacompra)
        vino.save()


@receiver(post_delete, sender=ComprasDet)
def detalle_compra_borrar(sender,instance, **kwargs):
    id_vino = instance.vino.id
    id_compra = instance.compra.id
    fecha_compra=instance.compra.fecha_compra

    enc = ComprasEnc.objects.filter(pk=id_compra).first()
    if enc:
        sub_total = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        print('--------------------' ,sub_total['sub_total__sum']) 
        if  sub_total['sub_total__sum'] is None or sub_total['sub_total__sum']==0:
            enc.total=0  
            print('!!!!!!!1funciona',enc.total) 
            enc.save()
        else:
            enc.total=sub_total['sub_total__sum']
            enc.save()
    
    vino=Vino.objects.filter(pk=id_vino).first()
    if vino:
        cant=int(instance.cantidad)
        ex=int(vino.existencia)
        if cant>ex:
            print('no se puede hacer')
        elif cant<=ex:
            cantidad = ex - cant
            vino.existencia = cantidad
            vino.ultimacompra=fecha_compra
            vino.save()

applications/compras/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import ComprasEnc


class ComprasEncForm(forms.ModelForm):
    fecha_compra = forms.DateInput()

    
    class Meta:
        model=ComprasEnc
        fields=['fecha_compra','observacion',
            'total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True
    
    def clean_fecha_compra(self):
        fecha_compra= self.cleaned_data.get('fecha_compra')
        print(fecha_compra)
        if fecha_compra=='':

            raise ValidationError('El campo fecha esta vacio')

applications/compras/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from django.views import generic
from django.urls import reverse_lazy
import datetime
from django.http import HttpResponse, JsonResponse

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.http import HttpResponse
import json
from django.db.models import Sum
from django.contrib.auth.decorators import login_required, permission_required
from applications.bases.views import SinPrivilegios
from .models import ComprasEnc, ComprasDet
from .forms import ComprasEncForm
#from bases.views import SinPrivilegios
from applications.vino.models import Vino




class ComprasView(SinPrivilegios,generic.ListView):
    model = ComprasEnc
    template_name = "compras/listacompras.html"
    context_object_name = "obj"
    permission_required='compras.view_comprasenc'
    


@login_required(login_url='/login/')
@permission_required('cmp.view_comprasenc', login_url='bases:sin_privilegios')
def compras(request,compra_id=None):
    template_name="compras/from2.html"
    vino=Vino.objects.filter(estado=True)
    print(vino)
    form_compras={}
    contexto={}

    if request.method=='GET':
        form_compras=ComprasEncForm()
        enc = ComprasEnc.objects.filter(pk=compra_id).first()

        if enc:
            det = ComprasDet.objects.filter(compra=enc)
            fecha_compra = datetime.date.isoformat(enc.fecha_compra)
            e = {
                'fecha_compra':fecha_compra,
                'observacion': enc.observacion,
                'total':enc.total
            }
            form_compras = ComprasEncForm(e)
        else:
            det=None
        
        contexto={'productos':vino,'encabezado':enc,'detalle':det,'form_enc':form_compras}

#METODO POST
    if request.method=='POST':
        fecha_compra = request.POST.get("fecha_compra")
        observacion = request.POST.get("observacion")
        total = 0

        if not compra_id:

            enc = ComprasEnc(
                fecha_compra=fecha_compra,
                observacion=observacion,
                uc = request.user 
            )
            if enc:
                enc.save()
                compra_id=enc.id
        else:
            enc=ComprasEnc.objects.filter(pk=compra_id).first()
            if enc:
                enc.fecha_compra = fecha_compra
                enc.observacion = observacion
                enc.um=request.user.id
                enc.save()

        if not compra_id:
            return redirect("compras:listacompras")
        
        producto = request.POST.get("id_codigo")
        cantidad = request.POST.get("id_cantidad_detalle")
        precio = request.POST.get("id_precio_detalle")
        sub_total_detalle = request.POST.get("id_sub_total_detalle")
        

        prod = Vino.objects.get(codigo=producto)
        print('producto',prod.id)
     
        det = ComprasDet(
            compra=enc,
            vino=prod,
            cantidad=cantidad,
            precio=precio,
            uc = request.user

        )

        if det:
            det.save()

            sub_total=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            enc.total = sub_total["sub_total__sum"]
            enc.save()

        return redirect("compras:editarcompra",compra_id=compra_id)


    return render(request, template_name, contexto)


class CompraDetDelete(PermissionRequiredMixin, generic.DeleteView):
    
    model = ComprasDet
    template_name = "compras/delete_detcompra.html"
    context_object_name = 'obj'
    permission_required = "compras.delete_comprasdet"
    def get_success_url(self):
          compra_id=self.kwargs['compra_id']
          return reverse_lazy('compras:editarcompra', kwargs={'compra_id': compra_id})

compras/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from django.views import generic
from django.urls import reverse_lazy
import datetime
from django.http import HttpResponse, JsonResponse

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.http import HttpResponse
import json
from django.db.models import Sum
from django.contrib.auth.decorators import login_required, permission_required

from .models import ComprasEnc, ComprasDet
from .forms import ComprasEncForm
#from bases.views import SinPrivilegios
from vino.models import Vino




class ComprasView(PermissionRequiredMixin,generic.ListView):
    model = ComprasEnc
    template_name = "compras/listacompras.html"
    context_object_name = "obj"
    permission_required='compras.view_comprasenc'





@login_required(login_url="/login/")
@permission_required("compras.view_comprasenc",login_url="/login/")

def compras(request,compra_id=None):
    template_name="compras/from2.html"
    vino=Vino.objects.filter(estado=True)
    print(vino)
    form_compras={}
    contexto={}

    if request.method=='GET':
        form_compras=ComprasEncForm()
        enc = ComprasEnc.objects.filter(pk=compra_id).first()

        if enc:
            det = ComprasDet.objects.filter(compra=enc)
            fecha_compra = datetime.date.isoformat(enc.fecha_compra)
            e = {
                'fecha_compra':fecha_compra,
                'observacion': enc.observacion,
                'total':enc.total
            }
            form_compras = ComprasEncForm(e)
        else:
            det=None
        
        contexto={'productos':vino,'encabezado':enc,'detalle':det,'form_enc':form_compras}

#METODO POST
    if request.method=='POST':
        fecha_compra = request.POST.get("fecha_compra")
        observacion = request.POST.get("observacion")
        total = 0

        if not compra_id:

            enc = ComprasEnc(
                fecha_compra=fecha_compra,
                observacion=observacion,
                uc = request.user 
            )
            if enc:
                enc.save()
                compra_id=enc.id
        else:
            enc=ComprasEnc.objects.filter(pk=compra_id).first()
            if enc:
                enc.fecha_compra = fecha_compra
                enc.observacion = observacion
                enc.um=request.user.id
                enc.save()

        if not compra_id:
            return redirect("compras:listacompras")
        
        producto = request.POST.get("id_codigo")
        cantidad = request.POST.get("id_cantidad_detalle")
        precio = request.POST.get("id_precio_detalle")
        sub_total_detalle = request.POST.get("id_sub_total_detalle")
        

        prod = Vino.objects.get(codigo=producto)
        print('producto',prod.id)
     
        det = ComprasDet(
            compra=enc,
            vino=prod,
            cantidad=cantidad,
            precio=precio,
            uc = request.user

        )

        if det:
            det.save()

            sub_total=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            enc.total = sub_total["sub_total__sum"]
            enc.save()

        return redirect("compras:editarcompra",compra_id=compra_id)


    return render(request, template_name, contexto)


class CompraDetDelete(PermissionRequiredMixin, generic.DeleteView):
    
    model = ComprasDet
    template_name = "compras/delete_detcompra.html"
    context_object_name = 'obj'
    permission_required = "compras.delete_comprasdet"
    def get_success_url(self):
          compra_id=self.kwargs['compra_id']
          return reverse_lazy('compras:editarcompra', kwargs={'compra_id': compra_id})

templates/compras/delete_detcompra.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form role="form" action="{% url 'compras:delete_detcompra' obj.compra.id obj.pk %}" method="post"  class="form-inline">
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Eliminar Detalle
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            ¿Eliminar {{ obj.vino }} de compra número <b>{{ obj.compra.id}} </b> ?
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

templates/compras/imprimirtodas.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Compras</title>

    <style type="text/css">
    @page {
        size: letter;
        margin: 1cm;
    }
    .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 5px;
        background-color: #fff;
    }
    .table th,
    .table td {
        padding: 5px;
        vertical-align: top;
        border-top: 1px solid #000;
        text-align: center;
    }
    .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #000;
    }
    .table tbody + tbody {
        border-top: 2px solid #000;
    }
    .table .table {
        background-color: #fff;
    }
    .list-group {
        display: block;
        width: 100%;
        list-style: none;
        margin-top: 15px;
        margin-bottom: 15px;
    }
    .list-group p {
        width: 100%;
        height: 20px;
        line-height: 20px;
        list-style: none;
        font-size: 1.1em;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>Sistema de stock</h2>
                <h3>Reporte de Compras al {{ today|date:"d/m/Y" }} por el usuario {{request.user}}</h3>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>No. Compra</th>
                        <th>Observacion</th>
                        <th>Fecha</th>
                        <th>Total</th>
                        <th>Usuario creador</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.observacion }}</td>
                        <td>{{ item.fecha_compra | date:"d/m/Y" }}</td>
                        <td>{{ item.total }}</td>
                        <td>{{item.uc}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

templates/compras/imprimiruna.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Compras</title>

    <style type="text/css">
    @page {
        size: letter;
        margin: 1cm;
    }

    .table td {
        text-align: center;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h4>Detalle de compra</h4>
            </div>
            <div class="row">
             <div class="row">   <div class="col-md-6"> <p>No. Compra: {{ encabezado.id}} </p>
                
                <h3>Fecha Compra</h3>
                 <h3> {{ encabezado.fecha_compra|date:"d/m/Y"}}</h3>
               
               </div></div>
                <div class="row">
                    <div class="col-md-6">
                        <h3>Observacion</h3>
                        <h3>{{encabezado.Observación}} </h3>
                     <h3>Total</h3>  
                     <h3>{{ encabezado.total}}</h3>
                    </div>
                </div>
            </div>


            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>#</th>
                    <th scope="col">Codigo</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Subtotal</th>
                  </tr>
                </thead>
                <tbody>
                    
                    {% for item in detalle %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{item.vino.codigo}}</td>
                        <td>{{item.vino}}</td>
                        <td>{{item.precio}}</td>
                        <td>{{item.cantidad}}</td>
                        <td>{{item.sub_total}}</td>
                      </tr>
                    {% endfor %}
           

              
              
                </tbody>
              </table>

           
        </div>
    </div>
</body>
</html>


<!--
     <table class="table">
                <thead>
                    <tr>
                  
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in detalle %}
                    <tr>
                        <td  >{{ item.vino}}</td>
                        <td class="numero">{{ item.cantidad }}</td>
                        <td class="numero">{{ item.precio}}</td>
                        <td class="numero">{{ item.sub_total }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                           
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                         
                          </tr>

                </tbody>
            </table>
-->

templates/compras/listacompras.html
{% extends 'base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Compras</h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" href="{% url 'compras:compras_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
        <a class="dropdown-item" href="{% url 'compras:imprimirtodas' %} " target="reportes"><i class="fas fa-print"></i> Listado</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay compras</div>
    {% endif %}
    <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%"
    id="table"
    data-toggle="table"
    data-pagination="true"
    data-search="true"
    data-show-columns="true"
    data-show-toggle="true"
    data-show-fullscreen="true"
    data-toolbar=".buttons-toolbar"
    data-locale="es-NI"
    
    >
      <thead>
        <th data-sortable="true" data-field="id"  >Id</th>        
        <th data-sortable="true" data-field="fecha" >Fecha</th>
        <th data-field="observacion" >Observación</th>
        <th data-sortable="total" data-field="total"   >Total</th>
        <th>Realizada por </th>
      
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in obj%}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.fecha_compra }}</td>
          <td>{{item.observacion}}</td>
          <td>{{ item.total }}</td>
          <td>{{item.uc}}</td>
          <!--<td>{{item.estado|yesno:"Activo,Inactivo"}}</td> --> 
          <td>
            <a class="btn btn-warning btn-circle" href="{% url 'compras:editarcompra' item.pk %}"><i class="far fa-edit"></i></a>
            <a class="btn btn-success btn-circle" href="{% url 'compras:imprimiruna' item.id %} " target="reportes"><i class="fas fa-print"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}

{% endblock %}

<!--
  <script>
/ *
$(document).ready(function() {
  $('.table').DataTable({
    "language": {
      "sProcessing": "Procesando...",
      "sLengthMenu": "Mostrar _MENU_ registros",
      "sZeroRecords": "No se encontraron resultados",
      "sEmptyTable": "Ningún dato disponible en esta tabla",
      "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
      "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
      "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
      "sInfoPostFix": "",
      "sSearch": "Buscar:",
      "sUrl": "",
      "sInfoThousands": ",",
      "sLoadingRecords": "Cargando...",
      "oPaginate": {
          "sFirst": "<span class='fa fa-angle-double-left'></span>",
          "sLast": "<span class='fa fa-angle-double-right'></span>",
          "sNext": "<span class='fa fa-angle-right'></span>",
          "sPrevious": "<span class='fa fa-angle-left'></span>"
      },
      "oAria": {
          "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
      }
    }
  });
}); * /
</script>
-->