app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('vino/',include(('applications.vino.urls' ,'vino'),namespace='vino')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/vino/urls.py
from django.urls import path , include 
from .views import CepaView ,CepaUpdate, UnidadView,UnidadNew,UnidadUpdate , BodegaView , ReservaView , VinoView,VinoNew,VinoUpdate ,CepaNew,BodegaNew,ReservaNew,BodegaUpdate,ReservaUpdate
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('cepas/',CepaView.as_view(),name='cepas'),
     path('cepas/new/',CepaNew.as_view(),name='cepanew'),
     path('cepas/cepaupdate/<int:pk>',CepaUpdate.as_view(),name='cepaupdate'),
    path('unidades/',UnidadView.as_view(),name='unidades'),
    path('unidades/unidadnew',UnidadNew.as_view(),name='crearunidad'),
    path('unidades/unidadupdate/<int:pk>/',UnidadUpdate.as_view(),name='unidadupdate'),
    path('reservas/',ReservaView.as_view(),name='reservas'),
    path('reservas/creareserva/',ReservaNew.as_view(),name='creareserva'),
     path('reservas/update/<int:pk>/',ReservaUpdate.as_view(),name='reservaupdate'),
    path('bodegas/',BodegaView.as_view(),name='bodegas'),
    path('bodegas/new/',BodegaNew.as_view(),name='crearbodega'),
    path('bodegas/update/<int:pk>/',BodegaUpdate.as_view(),name='bodegaupdate'),
    path('vinos/',VinoView.as_view(),name='vinos'),
    path('vinos/new/',VinoNew.as_view(),name='crearvino'),
    path('vinos/update/<int:pk>/',VinoUpdate.as_view(),name='vinoupdate'),
    
]

applications/vino/models.py
from django.db import models
from applications.bases.models import ClaseModelo2 , ClaseModelo


class Unidad(ClaseModelo2):
    medida=models.CharField(max_length=10)
    def __str__(self):
         return self.medida
class Bodega(ClaseModelo2):
    nombre=models.CharField(max_length=30)
    numero=models.CharField(max_length=30, blank=True ,null=True)
    email=models.CharField(max_length=30 ,blank=True ,null=True)
    def __str__(self):
        return self.nombre
class Reserva(ClaseModelo2):
    tipo=models.CharField(max_length=20)
    descripcion=models.CharField(max_length=50, blank=True ,null=True)
    def __str__(self):
        return self.tipo

class Cepa(ClaseModelo2):
    nombre=models.CharField(max_length=30)
    descripcion=models.CharField(max_length=100 , blank=True ,null=True)
    estado=models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
# Create your models here.
class Vino(ClaseModelo2):
    nombre=models.CharField(max_length=40)
    descripcion=models.CharField(max_length=100 , blank=True ,null=True)
    codigo=models.CharField(max_length=30 ,unique=True)
    precioventa=models.FloatField()
    reserva=models.ForeignKey(Reserva , on_delete=models.CASCADE)
    bodega=models.ForeignKey(Bodega ,blank=True,null=True, on_delete=models.CASCADE)
    cepa=models.ForeignKey(Cepa,blank=True,null=True,  on_delete=models.CASCADE)
    unidad=models.ForeignKey(Unidad, on_delete=models.CASCADE)
    existencia=models.IntegerField(default=0)
    ultimacompra=models.DateField(blank=True , null=True)
    sm=models.IntegerField(blank=True , null=True)
    

    def __str__(self):
            return '{}'.format(self.nombre)
class Meta:
        verbose_name_plural = "Productos"

  

applications/vino/views.py
from django.shortcuts import render
from .models import Cepa ,Vino ,Reserva,Bodega ,Unidad
# Create your views here.
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.views.generic import ListView ,UpdateView, CreateView ,TemplateView
from .forms import CepaNewForm ,ReservaNewForm,UnidadNewForm,VinoNewForm ,BodegaNewForm
from django.urls import reverse_lazy
#,BodegaNewForm 
from django.http import HttpResponse, JsonResponse
from applications.bases.views import SinPrivilegios


class MixinFormInvalid():
    def form_invalid(self , form):
        response=super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors , status=400)
        else:
            return response 



class CepaView(SinPrivilegios,ListView):
    model=Cepa
    context_object_name='obj'
    template_name='vinos/cepas.html'
    login_url='bases:login'
    permission_required='vino.view_cepa'
    
class CepaNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=Cepa
    form_class=CepaNewForm
    template_name='vinos/crearcepa.html'
    context_object_name='obj'
    success_url=reverse_lazy('vino:cepas')
    login_url='bases-login'
    permission_required='vino.add_cepa'
    success_message='Cepa creada satisfactoriamente'
class CepaUpdate(SuccessMessageMixin,SinPrivilegios, UpdateView):
    model=Cepa
    form_class=CepaNewForm
    template_name='vinos/crearcepa.html'
    context_object_name='obj'
    success_url=reverse_lazy('vino:cepas')
    login_url='bases-login'
    permission_required='vino.change_cepa'
    success_message='Cepa actualizada satisfactoriamente'
    #permission_required='vino.delete_cepa'

class BodegaView(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Bodega
    context_object_name='obj'
    template_name='vinos/bodegas.html'
    login_url='bases:login'
    permission_required='vino.view_bodega'
class BodegaNew(SuccessMessageMixin,SinPrivilegios, CreateView):
    model=Bodega
    form_class=BodegaNewForm
    context_object_name='obj'
    template_name='vinos/crearbodega.html'
    login_url='bases:login'
    success_url=reverse_lazy('vino:bodegas')
    permission_required='vino.add_bodega'
    success_message='Bodega creada exitosamente'
class BodegaUpdate(SuccessMessageMixin,SinPrivilegios, UpdateView):
    model=Bodega
    form_class=BodegaNewForm
    context_object_name='obj'
    template_name='vinos/crearbodega.html'
    login_url='bases:login'
    success_url=reverse_lazy('vino:bodegas')   
    permission_required='vino.change_bodega'
    success_message='Bodega editada exitosamente'
class ReservaView(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Reserva
    context_object_name='obj'
    template_name='vinos/reservas.html'
    login_url='bases:login'
    permission_required='vino.view_reserva'
  


    
    
    

class ReservaNew(SinPrivilegios,SuccessMessageMixin,CreateView):
    model=Reserva
    form_class=ReservaNewForm
    context_object_name='obj'
    template_name='vinos/crearreserva.html'
    success_url=reverse_lazy('vino:reservas')
    login_url='bases:login'
    permission_required='vino.add_reserva'
    success_message='Categoria creada exitosamente'
class ReservaUpdate(SuccessMessageMixin,SinPrivilegios,UpdateView):
    model=Reserva
    form_class=ReservaNewForm
    context_object_name='obj'
    template_name='vinos/crearreserva.html'
    success_url=reverse_lazy('vino:reservas')
    login_url='bases:login'
    permission_required='vino.change_reserva'
    success_message='Categoria editada exitosamente'
    #permission_required='vino.delete_reserva'

class UnidadView(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Unidad
    context_object_name='obj'
    template_name='vinos/unidades.html'
    login_url='bases:login'
    permission_required='vino.view_unidad'
    
class UnidadNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=Unidad
    form_class=UnidadNewForm
    context_object_name='obj'
    template_name='vinos/crearunidad.html'
    success_url=reverse_lazy('vino:unidades')
   
    permission_required='vino.add_unidad'
    success_message='Unidad creada exitosamente'
class UnidadUpdate(SuccessMessageMixin,SinPrivilegios,UpdateView):
    model=Unidad
    form_class=UnidadNewForm
    context_object_name='obj'
    template_name='vinos/crearunidad.html'
    success_url=reverse_lazy('vino:unidades')

    permission_required='vino.change_unidad'
    success_message='Unidad editada exitosamente'

    

class VinoView(SuccessMessageMixin,SinPrivilegios,ListView): 
    model=Vino
    context_object_name='obj'
    template_name='vinos/vinos.html'
    login_url='bases:login'
    permission_required='vino.view_vino'
class VinoNew(SuccessMessageMixin,MixinFormInvalid,SinPrivilegios,CreateView): 
    model=Vino
    form_class=VinoNewForm
    context_object_name='obj'
    template_name='vinos/modalvino.html'
    success_url=reverse_lazy('vino:vinos')
    login_url='bases:login'
    permission_required='vino.add_vino'
    success_message='Producto creado exitosamente'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

    
    def get_context_data(self , **kwargs):
        context=super(VinoNew , self).get_context_data(**kwargs)
        context['cepa']=Cepa.objects.filter(estado=True)
        context['bodega']=Bodega.objects.filter(estado=True)
        context['unidad']=Unidad.objects.filter(estado=True)
        context['reserva']=Reserva.objects.filter(estado=True)
        print(context)
        return context
class VinoUpdate(SuccessMessageMixin, MixinFormInvalid,SinPrivilegios,UpdateView): 
    model=Vino
    form_class=VinoNewForm
    context_object_name='obj'
    template_name='vinos/modalvino.html'
    success_url=reverse_lazy('vino:vinos')
    login_url='bases:login'
    permission_required='vino.change_vino'
    success_message='Producto editado exitosamente'
    #permission_required='vino.delete_vino'
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context=super(VinoUpdate , self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['cepa']=Cepa.objects.filter(estado=True)
        context['bodega']=Bodega.objects.filter(estado=True)
        context['unidad']=Unidad.objects.filter(estado=True)
        context['reserva']=Reserva.objects.filter(estado=True)
        context["obj"] = Vino.objects.filter(pk=pk).first()
        return context

vino/views.py
from django.shortcuts import render
from .models import Cepa ,Vino ,Reserva,Bodega ,Unidad
# Create your views here.
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.views.generic import ListView ,UpdateView, CreateView ,TemplateView
from .forms import CepaNewForm ,ReservaNewForm,UnidadNewForm,VinoNewForm ,BodegaNewForm
from django.urls import reverse_lazy
#,BodegaNewForm 
from django.http import HttpResponse, JsonResponse
from bases.views import SinPrivilegios


class MixinFormInvalid():
    def form_invalid(self , form):
        response=super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors , status=400)
        else:
            return response 



class CepaView(SinPrivilegios,ListView):
    model=Cepa
    context_object_name='obj'
    template_name='vinos/cepas.html'
    login_url='bases:login'
    permission_required='vino.view_cepa'
    
class CepaNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=Cepa
    form_class=CepaNewForm
    template_name='vinos/crearcepa.html'
    context_object_name='obj'
    success_url=reverse_lazy('vino:cepas')
    login_url='bases-login'
    permission_required='vino.add_cepa'
    success_message='Cepa creada satisfactoriamente'
class CepaUpdate(SuccessMessageMixin,SinPrivilegios, UpdateView):
    model=Cepa
    form_class=CepaNewForm
    template_name='vinos/crearcepa.html'
    context_object_name='obj'
    success_url=reverse_lazy('vino:cepas')
    login_url='bases-login'
    permission_required='vino.change_cepa'
    success_message='Cepa actualizada satisfactoriamente'
    #permission_required='vino.delete_cepa'

class BodegaView(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Bodega
    context_object_name='obj'
    template_name='vinos/bodegas.html'
    login_url='bases:login'
    permission_required='vino.view_bodega'
class BodegaNew(SuccessMessageMixin,SinPrivilegios, CreateView):
    model=Bodega
    form_class=BodegaNewForm
    context_object_name='obj'
    template_name='vinos/crearbodega.html'
    login_url='bases:login'
    success_url=reverse_lazy('vino:bodegas')
    permission_required='vino.add_bodega'
    success_message='Bodega creada exitosamente'
class BodegaUpdate(SuccessMessageMixin,SinPrivilegios, UpdateView):
    model=Bodega
    form_class=BodegaNewForm
    context_object_name='obj'
    template_name='vinos/crearbodega.html'
    login_url='bases:login'
    success_url=reverse_lazy('vino:bodegas')   
    permission_required='vino.change_bodega'
    success_message='Bodega editada exitosamente'
class ReservaView(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Reserva
    context_object_name='obj'
    template_name='vinos/reservas.html'
    login_url='bases:login'
    permission_required='vino.view_reserva'
  


    
    
    

class ReservaNew(SinPrivilegios,SuccessMessageMixin,CreateView):
    model=Reserva
    form_class=ReservaNewForm
    context_object_name='obj'
    template_name='vinos/crearreserva.html'
    success_url=reverse_lazy('vino:reservas')
    login_url='bases:login'
    permission_required='vino.add_reserva'
    success_message='Reserva creada exitosamente'
class ReservaUpdate(SuccessMessageMixin,SinPrivilegios,UpdateView):
    model=Reserva
    form_class=ReservaNewForm
    context_object_name='obj'
    template_name='vinos/crearreserva.html'
    success_url=reverse_lazy('vino:reservas')
    login_url='bases:login'
    permission_required='vino.change_reserva'
    success_message='Reserva editada exitosamente'
    #permission_required='vino.delete_reserva'

class UnidadView(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Unidad
    context_object_name='obj'
    template_name='vinos/unidades.html'
    login_url='bases:login'
    permission_required='vino.view_unidad'
    
class UnidadNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=Unidad
    form_class=UnidadNewForm
    context_object_name='obj'
    template_name='vinos/crearunidad.html'
    success_url=reverse_lazy('vino:unidades')
   
    permission_required='vino.add_unidad'
    success_message='Unidad creada exitosamente'
class UnidadUpdate(SuccessMessageMixin,SinPrivilegios,UpdateView):
    model=Unidad
    form_class=UnidadNewForm
    context_object_name='obj'
    template_name='vinos/crearunidad.html'
    success_url=reverse_lazy('vino:unidades')

    permission_required='vino.change_unidad'
    success_message='Unidad editada exitosamente'

    

class VinoView(SuccessMessageMixin,SinPrivilegios,ListView): 
    model=Vino
    context_object_name='obj'
    template_name='vinos/vinos.html'
    login_url='bases:login'
    permission_required='vino.view_vino'
class VinoNew(SuccessMessageMixin,MixinFormInvalid,SinPrivilegios,CreateView): 
    model=Vino
    form_class=VinoNewForm
    context_object_name='obj'
    template_name='vinos/modalvino.html'
    success_url=reverse_lazy('vino:vinos')
    login_url='bases:login'
    permission_required='vino.add_vino'
    success_message='Vino creado exitosamente'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

    
    def get_context_data(self , **kwargs):
        context=super(VinoNew , self).get_context_data(**kwargs)
        context['cepa']=Cepa.objects.filter(estado=True)
        context['bodega']=Bodega.objects.filter(estado=True)
        context['unidad']=Unidad.objects.filter(estado=True)
        context['reserva']=Reserva.objects.filter(estado=True)
        print(context)
        return context
class VinoUpdate(SuccessMessageMixin, MixinFormInvalid,SinPrivilegios,UpdateView): 
    model=Vino
    form_class=VinoNewForm
    context_object_name='obj'
    template_name='vinos/modalvino.html'
    success_url=reverse_lazy('vino:vinos')
    login_url='bases:login'
    permission_required='vino.change_vino'
    success_message='Vino editado exitosamente'
    #permission_required='vino.delete_vino'
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context=super(VinoUpdate , self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['cepa']=Cepa.objects.filter(estado=True)
        context['bodega']=Bodega.objects.filter(estado=True)
        context['unidad']=Unidad.objects.filter(estado=True)
        context['reserva']=Reserva.objects.filter(estado=True)
        context["obj"] = Vino.objects.filter(pk=pk).first()
        return context

vino/templates/vinos/bodegas.html
{% extends 'base/base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE BODEGAS</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" href="{% url 'vino:crearbodega' %}">Nueva</a>
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay bodegas
                 {% endif %}
                 <table class="table table-striped table-hover"
                 
                 id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
                 
                 
                 >
                    <thead>
                        <th data-sortable="true" data-field="nombre">Nombre</th>
     <th data-field="numero" >Numero</i></th>
     <th data-field="email">Email</th>
     <th  data-field="estado">Estado</th>
     <th  >Usuario creador</th>
    <th  class="all">Editar</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item.nombre}}</td>
        <td>{{item.numero}}</td>
        <td>{{item.email}}</td>
        <td>
          
          {% if  item.estado %}
          Activo
            {% else  %}
            Inactivo
          {% endif %}
            
         
        </td>
        <td>{{item.uc}}</td>
        <td>
            <a href="{% url 'vino:bodegaupdate' item.id %}" class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
<script>

     </script>
{% endblock js_page %}
    
    

vino/templates/vinos/cepas.html
{% extends 'base/base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE CEPAS</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" href="{% url 'vino:cepanew' %}" ><i class="far fa-calendar-plus"></i> Nueva</a>
                     
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay cepas
                 {% endif %}
                 <table class="table table-striped table-hover"
                 id="table"
                 data-toggle="table"
                 data-pagination="true"
                 data-search="true"
                 data-show-columns="true"
                 data-show-toggle="true"
                 data-show-fullscreen="true"
                 data-toolbar=".buttons-toolbar"
                 data-locale="es-NI"
                 >
                    <thead>
                  <th data-sortable="true" data-field="nombre">Nombre</th>
                  <th data-sortable="true">Descripcion</th>
     <th>Estado</th>
     <th>Usuario creador</th>
     
    <th class="all">Editar</th>
                    </thead>
<tbody>
    
  
      
   
      
    {% for item in obj  %}
    
   
    <tr>
        <td>{{item.nombre}}</td>
        <td>{{item.descripcion}}</td>
        
        <td> 
          
          {% if item.estado %}
            Activo
            {% else %}
            Inactivo
          {% endif %}
            

        </td>
        <td>{{item.uc}}</td>
        <td>
            <a href="{% url 'vino:cepaupdate' item.id %} "class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
    </tr> 
   
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}

{% endblock js_page %}
    
    

vino/templates/vinos/crearcepa.html
{% extends 'base/base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Cepa
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-10">
                            <div class="input-group">
                                <input type="text" name="nombre" maxlength="100" class="form-control" required id="id_nombre" placeholder="Nombre"
                                value="{% if obj %} {{ obj.nombre}} {% endif %}">
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group m-1">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                {% if obj.estado %} checked 
                                {% endif %}  >
                            </div>
                        </div> 
                        <div class="col-10">
                            <div class="input-group">
                                <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción"
                                value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                            </div>
                        </div>
                      
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'vino:cepas' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}
    
  {% block js_page %}
      
  {% endblock js_page %}
 

vino/templates/vinos/crearreserva.html
{% extends 'base/base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Reserva
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-10">
                            <div class="input-group ">
                                <input type="text" name="tipo" maxlength="100" class="form-control m-1" required id="id_tipo" placeholder="Tipo"
                                value="{% if obj %} {{ obj.tipo }} {% endif %}">
                            </div>
                        </div> 
                        <div class="col-10">
                            <div class="input-group ">
                                <input type="text" name="descripcion" maxlength="100" class="form-control m-1" required id="id_descripcion" placeholder="Descripcion"
                                value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                            </div>

                        </div>
                        <div class="col-2">
                            <div class="form-group m-1">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                {% if obj.estado %} checked {% endif %}  >
                            </div>
                        </div> 
                      
                      
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'vino:reservas' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}

vino/templates/vinos/crearunidad.html
{% extends 'base/base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Unidad
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-10">
                            <div class="input-group ">
                                <input type="text" name="medida" maxlength="100" class="form-control m-1" required id="id_medida" placeholder="Medida"
                                value="{% if obj %} {{ obj.medida}} {% endif %}">
                            </div>
                        </div> 
                      
                        <div class="col-2">
                            <div class="form-group m-1">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                {% if obj.estado %} checked 
                                {% endif %}  >
                            </div>
                        </div> 
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'vino:unidades' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}