app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('vino/',include(('applications.vino.urls' ,'vino'),namespace='vino')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/ventas/urls.py
from django.urls import path , include

from .views import ClienteView ,ClienteNew ,VinoView, ClienteEdit,VentaListView , Ventas ,borrar_detalle_factura
from .reportes import imprimir_factura_recibo ,imprimir_factura_list
urlpatterns = [
    path('clientes/' , ClienteView.as_view() , name='clientes'),
    path('clientes/new/' , ClienteNew.as_view() , name='cliente_new'),
    path('clientes/<int:pk>' , ClienteEdit.as_view() , name='cliente_edit'),
    path('ventas/' , VentaListView.as_view() , name='ventas'),
    path('ventas/ventanew/' ,Ventas , name='ventanew'),
    path('ventas/ventaedit/<int:id>' ,Ventas , name='ventaedit'),
    path('ventas/buscar/' ,VinoView.as_view() , name='buscar'),
    path('ventas/imprimirecibo/<int:id>' , imprimir_factura_recibo ,name='imprimirecibo') ,
    path('ventas/imprimirventas/<str:f1>/<str:f2>/' , imprimir_factura_list , name='imprimirventas'),
    path('ventas/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
]

applications/ventas/forms.py
from django import forms

from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model=Cliente
        fields=['nombre','tipo',
            'numero','email','direccion','estado']
        exclude = ['um','fm','fc']
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
            self.fields['numero'].widget.attrs['requiered']=False
            self.fields['email'].widget.attrs['requiered']=False
            self.fields['direccion'].widget.attrs['requiered']=False

applications/ventas/views.py
from django.shortcuts import render ,redirect
from .models import Cliente , FacturaDet ,FacturaEnc
from django.views import generic
from .forms import ClienteForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.http import HttpResponse
from datetime import datetime
from applications.vino.views import VinoView
from django.contrib import messages
from applications.vino.models import Vino
from django.contrib.auth.decorators import login_required, permission_required
from applications.bases.views import SinPrivilegios
from django.contrib.auth import authenticate
from .models import FacturaDet , FacturaEnc
# Create your views here.
class ClienteView(SinPrivilegios,generic.ListView):
    model = Cliente
    template_name = "ventas/clientes.html"
    context_object_name = "obj"
    permission_required='ventas.view_cliente'
  
class VistaBaseCreate(SuccessMessageMixin,SinPrivilegios, \
    generic.CreateView):
    context_object_name = 'obj'
    success_message="Cliente creado exitosamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin,SinPrivilegios, \
    generic.UpdateView):
    context_object_name = 'obj'
    success_message="Cliente modificado exitosamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class ClienteNew(VistaBaseCreate,SinPrivilegios):
    model=Cliente
    template_name="ventas/cliente_form.html"
    form_class=ClienteForm
    success_url= reverse_lazy("ventas:clientes")
    permission_required='ventas.add_cliente'
    success_message='Cliente creado exitosamente'
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    


class ClienteEdit(VistaBaseEdit,SinPrivilegios):
    model=Cliente
    template_name="ventas/cliente_form.html"
    form_class=ClienteForm
    success_url= reverse_lazy("ventas:clientes")
    permission_required='ventas.update_cliente'
    success_message='Cliente actualizado exitosamente'



class VentaListView(SinPrivilegios,generic.ListView):
    model = FacturaEnc
    context_object_name='obj'
    template_name = "ventas/ventas.html"
    permission_required='ventas.view_facturaenc'
    facs=FacturaEnc.objects.values('fecha')
    

#VISTA DE FUNCIONES
@login_required(login_url="/login/")
@permission_required("ventas.view_facturaenc",login_url="bases:sin_privilegios")

def Ventas(request , id=None):
    template_name='ventas/venta_form.html'
    encabezado={
        'fecha':datetime.today()
    }
    detalle={}
    clientes=Cliente.objects.filter(estado=True)
    

    if request.method=='GET':
        enc=FacturaEnc.objects.filter(pk=id).first()
        if not enc:
            encabezado={
                'id':0,
                'fecha':datetime.today(),
                'cliente':0,
                'sub_total':0.00 ,
                'descuento':0.00 ,
                'total': 0.00
        
            }
            detalle=None
        else:
            encabezado={
                'id':enc.id,
                'fecha':enc.fecha,
                'cliente':enc.cliente,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'total':enc.total


            }
          



        detalle=FacturaDet.objects.filter(factura=enc)
        contexto = {"enc":encabezado,"det":detalle,"clientes":clientes}
        return render(request,template_name,contexto)

    if request.method=='POST':
        cliente=request.POST.get("enc_cliente")
      
        fecha=request.POST.get("enc_fecha")
        cli=Cliente.objects.get(pk=cliente)
      

        if not id:
            enc=FacturaEnc(
                cliente=cli,
                fecha=fecha,
                uc=request.user

            )
            if enc:
                enc.save()
                id=enc.id
        else:
            enc=FacturaEnc.objects.filter(pk=id).first()
            if enc:
                enc.cliente=cli
                enc.save()
        if not id:
            messages.error(request , "No se puede continuar ,Numero de factura no detectado")
            return redirect("ventas:ventas")

        codigo=request.POST.get("codigo")
        cantidad=request.POST.get("cantidad")
        precio=request.POST.get("precio")
        s_total=request.POST.get("sub_total_detalle")
        descuento=request.POST.get("descuento_detalle")
        total=request.POST.get("total")

        prod=Vino.objects.get(codigo=codigo)


        det=FacturaDet(
            factura=enc,
            vino=prod,
            cantidad=cantidad,
            precio=precio,
            sub_total=s_total,
            descuento=descuento,
            total=total,
            uc=request.user
            )
        if det:
            det.save()
        return redirect('ventas:ventaedit',id=id)



    return render(request , template_name, contexto)

class VinoView(VinoView):
    template_name='ventas/buscar_producto.html'

def borrar_detalle_factura(request, id):
    template_name = "ventas/borrar_detalle.html"

    det = FacturaDet.objects.get(pk=id)

    if request.method=="GET":
        context={"det":det}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")

        user =authenticate(username=usr,password=pas)

        if not user:
            return HttpResponse("Usuario o Clave Incorrecta")
        
        if not user.is_active:
            return HttpResponse("Usuario Inactivo")

        if user.is_superuser or user.has_perm("ventas.sup_caja_facturadet"):
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = (-1 * det.sub_total)
            det.descuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.save()

            return HttpResponse("ok")

        return HttpResponse("Usuario no autorizado")
    
    return render(request,template_name,context)

ventas/views.py
from django.shortcuts import render ,redirect
from .models import Cliente , FacturaDet ,FacturaEnc
from django.views import generic
from .forms import ClienteForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.http import HttpResponse
from datetime import datetime
from vino.views import VinoView
from django.contrib import messages
from vino.models import Vino
from django.contrib.auth.decorators import login_required, permission_required
from bases.views import SinPrivilegios
from django.contrib.auth import authenticate
from .models import FacturaDet , FacturaEnc
# Create your views here.
class ClienteView(SinPrivilegios,generic.ListView):
    model = Cliente
    template_name = "ventas/clientes.html"
    context_object_name = "obj"
    permission_required='ventas.view_cliente'
  
class VistaBaseCreate(SuccessMessageMixin,SinPrivilegios, \
    generic.CreateView):
    context_object_name = 'obj'
    success_message="Cliente creado exitosamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin,SinPrivilegios, \
    generic.UpdateView):
    context_object_name = 'obj'
    success_message="Cliente modificado exitosamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class ClienteNew(VistaBaseCreate,SinPrivilegios):
    model=Cliente
    template_name="ventas/cliente_form.html"
    form_class=ClienteForm
    success_url= reverse_lazy("ventas:clientes")
    permission_required='ventas.add_cliente'
    success_message='Cliente creado exitosamente'
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    


class ClienteEdit(VistaBaseEdit,SinPrivilegios):
    model=Cliente
    template_name="ventas/cliente_form.html"
    form_class=ClienteForm
    success_url= reverse_lazy("ventas:clientes")
    permission_required='ventas.update_cliente'
    success_message='Cliente actualizado exitosamente'



class VentaListView(SinPrivilegios,generic.ListView):
    model = FacturaEnc
    context_object_name='obj'
    template_name = "ventas/ventas.html"
    permission_required='ventas.view_facturaenc'

#VISTA DE FUNCIONES
@login_required(login_url="/login/")
@permission_required("ventas.view_facturaenc",login_url="/login/")

def Ventas(request , id=None):
    template_name='ventas/venta_form.html'
    encabezado={
        'fecha':datetime.today()
    }
    detalle={}
    clientes=Cliente.objects.filter(estado=True)
    

    if request.method=='GET':
        enc=FacturaEnc.objects.filter(pk=id).first()
        if not enc:
            encabezado={
                'id':0,
                'fecha':datetime.today(),
                'cliente':0,
                'sub_total':0.00 ,
                'descuento':0.00 ,
                'total': 0.00
        
            }
            detalle=None
        else:
            encabezado={
                'id':enc.id,
                'fecha':enc.fecha,
                'cliente':enc.cliente,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'total':enc.total


            }
          



        detalle=FacturaDet.objects.filter(factura=enc)
        contexto = {"enc":encabezado,"det":detalle,"clientes":clientes}
        return render(request,template_name,contexto)

    if request.method=='POST':
        cliente=request.POST.get("enc_cliente")
      
        fecha=request.POST.get("enc_fecha")
        cli=Cliente.objects.get(pk=cliente)
      

        if not id:
            enc=FacturaEnc(
                cliente=cli,
                fecha=fecha,
                uc=request.user

            )
            if enc:
                enc.save()
                id=enc.id
        else:
            enc=FacturaEnc.objects.filter(pk=id).first()
            if enc:
                enc.cliente=cli
                enc.save()
        if not id:
            messages.error(request , "No se puede continuar ,Numero de factura no detectado")
            return redirect("ventas:ventas")

        codigo=request.POST.get("codigo")
        cantidad=request.POST.get("cantidad")
        precio=request.POST.get("precio")
        s_total=request.POST.get("sub_total_detalle")
        descuento=request.POST.get("descuento_detalle")
        total=request.POST.get("total")

        prod=Vino.objects.get(codigo=codigo)


        det=FacturaDet(
            factura=enc,
            vino=prod,
            cantidad=cantidad,
            precio=precio,
            sub_total=s_total,
            descuento=descuento,
            total=total,
            uc=request.user
            )
        if det:
            det.save()
        return redirect('ventas:ventaedit',id=id)



    return render(request , template_name, contexto)

class VinoView(VinoView):
    template_name='ventas/buscar_producto.html'

def borrar_detalle_factura(request, id):
    template_name = "ventas/borrar_detalle.html"

    det = FacturaDet.objects.get(pk=id)

    if request.method=="GET":
        context={"det":det}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")

        user =authenticate(username=usr,password=pas)

        if not user:
            return HttpResponse("Usuario o Clave Incorrecta")
        
        if not user.is_active:
            return HttpResponse("Usuario Inactivo")

        if user.is_superuser or user.has_perm("ventas.sup_caja_facturadet"):
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = (-1 * det.sub_total)
            det.descuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.save()

            return HttpResponse("ok")

        return HttpResponse("Usuario no autorizado")
    
    return render(request,template_name,context)

templates/ventas/borrar_detalle.html
<label class="text-danger">¿Anular Producto <b>{{det.producto.descripcion}}</b> de venta <b>{{det.factura.id}}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" id="usuario" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

templates/ventas/buscar_producto.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Buscar Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        
                        <div class="row">
                                <table
                                id="tblProducto"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-show-fullscreen="true"
                                data-locale="es-NI"
                                >
                                <thead>
                                  <th data-sortable="true" data-field="id">Id</th>        
                                  <th data-sortable="true" data-field="codigo">Código</th>
                                  <th data-sortable="true" data-field="codigo_barra">Barra</th>
                                  <th data-field="descripcion">Descripción</th>
                                  <th data-field="existencia">Existencia</th>
                                  <th data-field="precioventa">Precio</th>
                                  <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                  {% for item in obj%}
                                  <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.nombre }}</td>
                                    <td>{{ item.codigo }}</td>
                                    <td>{{item.descripcion}}</td>
                                    <td>{{item.existencia}}</td>
                                    <td>{{item.precioventa}}</td>
                                    <td>
                                     {% if item.existencia > 0 and item.estado %}
                                     
                                
                                     <button class="btn btn-warning btn-circle" id="btnSelect" 
                                     onclick="seleccionarProducto({{item.id}},'{{item.codigo}}','{{item.descripcion}}','{{item.existencia}}',{{item.precioventa}} )"> <i class="far fa-hand-pointer"></i></button>
                                           
                                        </button>
                                        {% endif %}
                                    </td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" id="btnCancelar" class="btn btn-success">
                                        <!-- onclick="return cerrar_modal()" -->
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% block js_page %}
<script>
    $(function () {

        $("#btnCancelar").click(function(e){
            e.preventDefault();
            cerrar_modal();

        });
    });
    $('#tblProducto').bootstrapTable();

    function seleccionarProducto(id,codigo,descripcion,existencia,precioventa){
        $("#codigo").val(codigo);
        $("#descripcion").val(descripcion);
        $("#existencia").val(existencia);
        $("#precio").val(precioventa);
        $("#btnCancelar").click();
        $("#codigo").select();
        $("#codigo").focus();

    }

</script>
{% endblock %}

<!--
  
-->

templates/ventas/cliente_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form role="form" action="{% url 'ventas:cliente_edit' obj.pk %}" method="post"  class="form-inline">
        {% else %}
        <form role="form" action="{% url 'ventas:cliente_new' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Cliente
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

templates/ventas/clientes.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE CLIENTES</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      
                    </a>
                 
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay cliente
                 {% endif %}
                 <div class="buttons-toolbar"> <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'ventas:cliente_new' %}')"><i class="far fa-calendar-plus"></i>Nueva</a></div>
                 <table data-toggle="table"
                 id="table"

                 data-pagination="true" 
                 data-search="true"
                 data-show-columns="true"
                 data-show-toggle="true"
                 data-show-fullscreen="true"
                 data-toolbar=".buttons-toolbar"
                 data-locale="es-AR"

                 >
                    <thead>
   <th data-sortable="true" data-field="id" >id</th>
    <th data-sortable="true" data-field="nombre" >nombre</th>
    <th data-sortable="true" data-field="tipo" >tipo</th>
     <th data="numero" >numero</i></th>
     <th  data="email"  >email</th>
 
     <th data="estado"  >estado</th>
    <th class="all">Editar</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
      <td>{{item.id}}</td>
        <td>{{item.nombre}}</td>
        <td>{{item.tipo}}</td>
        <td>{{item.numero}}</td>
        
        <td>{{item.email}}</td>
      
        <td >{{item.estado|yesno:"Activo,Inactivo"}}
        </td> 
    <td>
      <button type="submit" class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'ventas:cliente_edit' item.id %}')"><i class="far fa-edit"></i></button>
 
         
        </td>  
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}
{% block js_page %}

<script>

     </script>
{% endblock %}
    

templates/ventas/imprimirecibo.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Recibo</title>
    <link rel="stylesheet" href="{% static 'base/css/recibo.css' %}">
    <style type="text/css">
       @page {
        size: letter;
        margin: 1cm;
    }

    .table td {
        text-align: center;
    }
    </style>
</head>
<body >
    <div class="col-md-1 col-sm-1 col-xs-1 col-xl-1">
        <center>
            <b class="text-center">Vinoteca</b><br> 
            <small>Direccion</small><br>
            
        </center>
        <small>
            <br>
            <b>Factura No.:</b>&nbsp;&nbsp;{{enc.id}}&nbsp;&nbsp;
            <b>Fecha Fact:</b>&nbsp;&nbsp;{{enc.fecha}}&nbsp;&nbsp; <br>
            <b>Cliente:</b>&nbsp;&nbsp; {{enc.cliente}}<br>
            <br><br>
        </small>
        <table class="table table-condensed table-sm" width="60%">
            <thead>
                <th>Código</th>
                <th  align='right'>Cant.</th>
                <th  align='right'>P. Unit.</th>
                <th  align='right'>Sub Total</th>
                <th  align='right'>Descuento</th>
                <th  align='right'>Total</th>
            </thead>
            <tbody>
                {% for obj in detalle %}
                <tr>
                    <td>{{obj.vino.codigo}}</td>
                    <td>{{obj.cantidad}}</td>
                    <td>{{obj.precio}}</td>
                    <td>{{obj.sub_total}}</td>
                    <td>{{obj.descuento}}</td>
                    <td>{{obj.total}}</td>
                </tr>
                <tr>
                    <td colspan="5">{{obj.producto}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="col-xs-1"></div>
        <div class="col-xs-11">
            <div class="pull-right">
            <table class="table-responsive dt-responsive nowrap">
                <thead>
                    <th colspan=2>Totales</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Sub Total:</td> <td align='right'>{{enc.sub_total}}</td>
                    </tr>
                    <tr>
                        <td>Descuento</td> <td align='right'>{{enc.descuento}}</td>
                    </tr>
                    <tr>
                        <td>Total:</td> <td align='right'><b>{{enc.total}}</b></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
        <div class="row">
        <small class="pie">
            <br><br>
            <center>
                Creada por:  {{enc.uc}} - Fecha:  {{enc.fc}}
                <br>
               
            </center>
        </small>
        </div>
    </div>
</body>
</html>
<!--  <i>&copy; &reg; <b></b><br></i>  -->

templates/ventas/ventas.html
{% extends 'base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de ventas</h6>
  
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <input type="text" class="form-class" name="f1" id="f1" readonly>
      </div>
      <div class="col-md-4">
        <input type="text" class="form-class" name="f2" id="f2" readonly>
      </div>
      <div class="col-md-4">
        <button class="btn btn-warning" type="button" id="btnPrint">Imprimir</button>
        
      </div>
    </div>
    <hr>

    
    {% if not obj %}
    <div class="alert alert-info">No Hay Ventas</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success" href="{% url 'ventas:ventanew' %}"><i cass="far fa-calendar-plus"></i> Nuevo</a>
    </div>

    <table 
    id="table"
    data-toggle="table"
    data-pagination="true"
    data-search="true"
    data-show-columns="true"
    data-show-toggle="true"
    data-show-fullscreen="true"
    data-toolbar=".buttons-toolbar"
    data-locale="es-NI"
  >
  <thead>
    <th data-sortable="true" data-field="id">No.</th>        
    <th data-sortable="true" data-field="nombres">Cliente</th>
    <th data-sortable="true" data-field="apellidos">Total</th>
    <th data-field="estado">Fecha</th>
    <th>Por</th>
    <th class="all">Editar</th>
  </thead>
  <tbody>
    {% for item in obj%}
    <tr>
      <td>{{ item.id }}</td>
      <td>{{ item.cliente }}</td>
      <td>{{ item.total }}</td>
      <td>{{item.fecha}}</td>
      <td>{{item.uc}}</td>
      <td>
        <a href="{% url 'ventas:ventaedit' item.id %}" i class="href btn btn-warning btn-circle">
            <i class="far fa-edit"></i>
        </a>
        <a class="btn btn-success btn-circle" href="{% url 'ventas:imprimirecibo' item.id %}" target="reportes"><i class="fas fa-print"></i></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>


  </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
$(function(){
  $("#f1, #f2").datetimepicker({
      format: 'Y-m-d',
      timepicker:false
  });

  $("#btnPrint").click(function(e){
    e.preventDefault();
    var f1,f2;
    f1 = $("#f1").val();
    f2 = $("#f2").val();
    if(f1=="" || f1==null){
      f1="2019-06-01";
    }
    if(f2=="" || f2==null){
      var d = new Date();
      var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
    }
    
    var url = "imprimirventas/" + f1 + "/" + f2;

    window.open(url,'ventas');
    
  });
});
</script>
{% endblock %}