app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('vino/',include(('applications.vino.urls' ,'vino'),namespace='vino')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/bases/urls.py
from django.urls import path , include 
from .views import Home , Dashboard , HomeSinPrivilegios
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Dashboard  ,name='dashboard'),
    path('home',Home  ,name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='bases/login.html'),name='logout'),
      #path('dashboard/' , Dashboard , name='dashboard'),
      
    path('sin_privilegios/',HomeSinPrivilegios.as_view(),name='sin_privilegios'),
    #path('dashboard/' , Dashboard , name='dashboard'),
]

applications/compras/urls.py
from django.urls import path , include

from .views import ComprasView, compras ,CompraDetDelete 
from .reportes import reporte_compras ,imprimir_compra

urlpatterns=[
    path('compras/',ComprasView.as_view(), name="listacompras"),
    path('compras/new',compras, name="compras_new"),
    path('compras/edit/<int:compra_id>',compras, name="editarcompra"),
    path('compras/<int:compra_id>/delete/<int:pk>',CompraDetDelete.as_view(), name="delete_detcompra"),
    path('compras/imprimirreportes/' ,reporte_compras, name='imprimirtodas'),
    path('compras/imprimiruna/<int:compra_id>/' , imprimir_compra , name='imprimiruna' ),
]

applications/ventas/urls.py
from django.urls import path , include

from .views import ClienteView ,ClienteNew ,VinoView, ClienteEdit,VentaListView , Ventas ,borrar_detalle_factura
from .reportes import imprimir_factura_recibo ,imprimir_factura_list
urlpatterns = [
    path('clientes/' , ClienteView.as_view() , name='clientes'),
    path('clientes/new/' , ClienteNew.as_view() , name='cliente_new'),
    path('clientes/<int:pk>' , ClienteEdit.as_view() , name='cliente_edit'),
    path('ventas/' , VentaListView.as_view() , name='ventas'),
    path('ventas/ventanew/' ,Ventas , name='ventanew'),
    path('ventas/ventaedit/<int:id>' ,Ventas , name='ventaedit'),
    path('ventas/buscar/' ,VinoView.as_view() , name='buscar'),
    path('ventas/imprimirecibo/<int:id>' , imprimir_factura_recibo ,name='imprimirecibo') ,
    path('ventas/imprimirventas/<str:f1>/<str:f2>/' , imprimir_factura_list , name='imprimirventas'),
    path('ventas/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
]

applications/vino/urls.py
from django.urls import path , include 
from .views import CepaView ,CepaUpdate, UnidadView,UnidadNew,UnidadUpdate , BodegaView , ReservaView , VinoView,VinoNew,VinoUpdate ,CepaNew,BodegaNew,ReservaNew,BodegaUpdate,ReservaUpdate
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('cepas/',CepaView.as_view(),name='cepas'),
     path('cepas/new/',CepaNew.as_view(),name='cepanew'),
     path('cepas/cepaupdate/<int:pk>',CepaUpdate.as_view(),name='cepaupdate'),
    path('unidades/',UnidadView.as_view(),name='unidades'),
    path('unidades/unidadnew',UnidadNew.as_view(),name='crearunidad'),
    path('unidades/unidadupdate/<int:pk>/',UnidadUpdate.as_view(),name='unidadupdate'),
    path('reservas/',ReservaView.as_view(),name='reservas'),
    path('reservas/creareserva/',ReservaNew.as_view(),name='creareserva'),
     path('reservas/update/<int:pk>/',ReservaUpdate.as_view(),name='reservaupdate'),
    path('bodegas/',BodegaView.as_view(),name='bodegas'),
    path('bodegas/new/',BodegaNew.as_view(),name='crearbodega'),
    path('bodegas/update/<int:pk>/',BodegaUpdate.as_view(),name='bodegaupdate'),
    path('vinos/',VinoView.as_view(),name='vinos'),
    path('vinos/new/',VinoNew.as_view(),name='crearvino'),
    path('vinos/update/<int:pk>/',VinoUpdate.as_view(),name='vinoupdate'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Sistema de stock</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'base/css/forms.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  

  
  <!-- Custom styles for this templat
-->
  <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css' %}" >
<link  href="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.css' %}">

<!--datetimepicker-->
<link  href="{% static 'base/css/jquery.datetimepicker.min.css' %}">


<!--datetimepicker-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />   
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />

<!-- bootstrap table-->
<link rel="stylesheet" href="{% static 'base/vendor/bootstrap-table-master/dist/bootstrap-table.min.css' %}">

<link rel="stylesheet" href="{% static 'base/vendor/select2-4.0.12/dist/css/select2.min.css' %}">
</head>

<body id="page-top">

{% block side_bar %}
  

  
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon rotate-n-15">
         
        </div>
        <div class="sidebar-brand-text mx-3">Carniceria</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bases:dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Panel de control</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        OPCIONES DE MENU
      </div>
{% url 'vino:cepas' as cepa_url %}
{% url 'vino:bodegas' as bodega_url %}
{% url 'vino:reservas' as reser_url %}
{% url 'vino:unidades' as uni_url %}
{% url 'vino:vinos' as vino_url %}
{% url 'compras:listacompras' as compras_url %}
{% url 'ventas:clientes' as clientes_url %}
{% url 'ventas:ventas' as ventas_url %}
      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item 
      {%  if cepa_url in request.path or bodega_url in request.path or  reser_url in request.path %}
        active
      {% endif %}
          ">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>CATALOGOS</span>
        </a>
        <div id="collapseTwo" class="collapse  {% if cepa_url in request.path or bodega_url in request.path or  reser_url in request.path or uni_url in request.path %}
        show
      {% endif %} " aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">CATALOGOS DE INVENTARIO</h6>

          
            <a class="collapse-item" href="{{reser_url}}">Categorias</a>
           
            <a class="collapse-item" href="{{uni_url}}">Unidades</a>
            
            <a class="collapse-item" href="{{vino_url}}">Productos</a>
              
              {% if perms.compras.view_comprasenc %}
              <a class="collapse-item" href="{{compras_url}}">Compras</a  >
              {% endif %}
                
          
              {% if perms.ventas.view_clientes %}
            <a class="collapse-item" href="{{clientes_url}}">Clientes</a>
            {% endif %}
            {% if perms.ventas.view_facturaenc %}
            <a class="collapse-item" href="{{ventas_url}}">Ventas</a>
            {% endif %}
       
          </div>
        </div>
      </li>


      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
 
    </ul>
    {% endblock side_bar %}
 
  
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% block top_bar %}
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
     

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                       
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
          
              <!-- Dropdown - Alerts -->
            

            <!-- Nav Item - Messages -->
            

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user}}</span>
                <img class="img-profile rounded-circle" src="{% static 'base/img/user.png' %}">
              </a>



              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
               
               
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Salir
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->
        {% endblock top_bar %}

        
        {% block page_content %}
          
        
          
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800"></h1>

        </div>
        {% endblock page_content %}
        <!-- /.container-fluid -->


  
  
      </div>
      <!-- End of Main Content -->
      {% block footer %}
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span></span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->
   

  </div>
  {% endblock footer %}
  <!-- End of Page Wrapper -->

{% block login %}{% endblock login %}
  

  
  
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Quieres salir?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Presiona el boton para cerrar la sesion actual en este sistema</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="{%  url 'bases:logout' %}">Cerrar Sesion</a>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="popup"></div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}" ></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.js'%}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'base/js/sb-admin-2.min.js' %}"></script>
 
    
  <script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  
  <script src="{% static 'base/js/jquery.datetimepicker.full.min.js' %}"></script>

 
  
  
  <script src="{% static 'base/vendor/bootstrap-table-master/dist/bootstrap-table.min.js' %} "></script>
  <script src="{% static 'base/vendor/bootstrap-table-master/dist/locale/bootstrap-table-es-AR.min.js' %} "></script>
  <script src="{% static 'base/vendor/select2-4.0.12/dist/js/select2.min.js' %}"></script>
  <!--Ventanas de mensajes-->
  <script src=" {% static 'base/js/sweetalert/sweetalert.js' %} "></script>
  <script>


    $(document).ready(function () {
      jQuery.datetimepicker.setLocale('es');
    });
</script>

 
  
{% block control_modal%}
 <script>
  

   function abrir_modal(url){
     $("#popup").load(url , function(){
      $(this).modal({
        backdrop:'static',
        keyboard: false
      })
       $(this).modal('show');
     });
     }
     function cerrar_modal()
     {
       $('#popup').modal('hide');
       return false;
       
     }
     
                function mensaje(mensaje, icon){
                  Swal.fire({
                  text: mensaje,
                  icon: icon,
                  confirmButtonText: 'OK'
            })

                }
                {% if messages %}
      {% for message in messages %}
        console.log("{{ message.tags }}");
        mensaje("{{ message }}","{{ message.tags }}");
      {% endfor %}
    {% endif %}
    

 </script>
    {% endblock%}
  {% block js_page %}{% endblock js_page %}
</body>

</html>

<!--
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>

    function mensaje(msg , color='green'){
      $.alert({
        title:'',
        theme:'material',
        type:color,
        content:msg
      });
    }
-->